# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a69dec04a3a313f8c56f2d8803aa1b9363ef13e5c70ebe7bcf107c44079d6bd4f99eebef1bb803d7d9c22b9bf02ffa17279bb621ec81833331ef08c1dc5fac2

test:
  secret_key_base: 74d21a2336108351bba3fb030aa2e387c64cb8d770d1b923b97655e5231b5f5a5e030fc3face60b9918aba1e3d46fbef385e047fe211388cab1b2fab3f112870

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
